using System;
using FluentAssertions;
using GoC.WebTemplate.Components.Utils.Caching;
using Xunit;

namespace GoC.WebTemplate.Components.Test.UtilTests
{
    public class LoadStaticFileTest
    {
        [Theory, AutoNSubstituteData]
        public void LoadStaticFileFromCache(Model sut)
        {
            var result = sut.LoadStaticFile("refTop.html");
            /// Cache is autoGenerated so file will be empty
            result.ToString().Should().Be("");
        }


        [Theory, AutoNSubstituteData]
        public void LoadStaticFile(IFileContentCacheProvider cacheProvider)
        {
            var sut = new FileContentCache(cacheProvider);
            var result = sut.LoadFile($"{AppContext.BaseDirectory.Substring(0, AppContext.BaseDirectory.IndexOf("bin"))}appsettings.json");
            result.Should().NotBeEmpty();
        }
    }
}
